inherit_from: .rubocop_todo.yml

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Naming/MethodName:
  EnforcedStyle: snake_case
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Lint/SuppressedException:
  Exclude:
    - 'spec/palletjack-tool_spec.rb'
Style/Not:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'tools/exe/palletjack2ipahost'
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Style/RedundantReturn:
  Exclude:
    - 'lib/palletjack/tool.rb'
Style/RescueStandardError:
  Exclude:
    - 'lib/palletjack/tool.rb'
Style/TrailingUnderscoreVariable:
  Enabled: false
