galaxy_info:
  author: Karl-Johan Karlsson
  description: Install and configure a LigHTTPd server providing Kickstart and Preseed netinstall recipes
  issue_tracker_url: https://github.com/creideiki/palletjack/issues
  license: MIT
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
      - 8
  galaxy_tags: []
